---
apiVersion: v1
kind: Service
metadata:
  name: llm-mini-service
  labels:
    app: mini-svc
spec:
  ports:
  - port: 9001
    targetPort: 9001
  selector:
    app: llm-mini
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: llm-turbo-service
  labels:
    app: turbo-svc
spec:
  ports:
  - port: 9002
    targetPort: 9002
  selector:
    app: llm-turbo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: llm-phi-service
  labels:
    app: phi-svc
spec:
  ports:
  - port: 9003
    targetPort: 9003
  selector:
    app: llm-phi
  type: NodePort