apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: streamlit-web
        image: streamlit-web
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-web-service
  labels:
    app: web
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: web
  type: NodePort