apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-executor
  labels:
    app: llm-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-executor
  template:
    metadata:
      labels:
        app: llm-executor
    spec:
      containers:
      - name: llm-executor
        image: llm-executor
        imagePullPolicy: Never
        command: ["fastapi", "run", "app/main.py", "--port", "8002"]
        envFrom:
        - configMapRef:
            name: llm-executor-config
---
apiVersion: v1
kind: Service
metadata:
  name: llm-executor-service
  labels:
    app: executor-svc
spec:
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: llm-executor
  type: NodePort